// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlAkydXYXBpXyf3qck9vOkJj2R6jVzjUs',
    appId: '1:268078085871:web:0d8c88fa1dbbdb7dfd4d1a',
    messagingSenderId: '268078085871',
    projectId: 'bookswap-f7258',
    authDomain: 'bookswap-f7258.firebaseapp.com',
    storageBucket: 'bookswap-f7258.firebasestorage.app',
    measurementId: 'G-H733KTG9HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3VLkeVrBiRuC9anmRbI2eUmuaIbH6LBw',
    appId: '1:268078085871:android:93759ee96c49ca99fd4d1a',
    messagingSenderId: '268078085871',
    projectId: 'bookswap-f7258',
    storageBucket: 'bookswap-f7258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5lBl6hVll3hWniXIysot9tEOHkRPfI0',
    appId: '1:268078085871:ios:0636b56f5cd597acfd4d1a',
    messagingSenderId: '268078085871',
    projectId: 'bookswap-f7258',
    storageBucket: 'bookswap-f7258.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5lBl6hVll3hWniXIysot9tEOHkRPfI0',
    appId: '1:268078085871:ios:0636b56f5cd597acfd4d1a',
    messagingSenderId: '268078085871',
    projectId: 'bookswap-f7258',
    storageBucket: 'bookswap-f7258.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlAkydXYXBpXyf3qck9vOkJj2R6jVzjUs',
    appId: '1:268078085871:web:c25fe5c92f15ab33fd4d1a',
    messagingSenderId: '268078085871',
    projectId: 'bookswap-f7258',
    authDomain: 'bookswap-f7258.firebaseapp.com',
    storageBucket: 'bookswap-f7258.firebasestorage.app',
    measurementId: 'G-DYXDX7MRKY',
  );
}
